services:
  db:
    image: postgres:16.11
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=workshop
      - POSTGRES_DB=lms

  ui:
    image: dpage/pgadmin4:9.10.0
    ports:
      - 5430:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=db@example.com
      - PGADMIN_DEFAULT_PASSWORD=secret
